[package]
name = "XElement"
version = "0.1.0"
authors = ["aFuzzyBear <afuzzybear@outlook.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
stork-search = "1.3.0"