
[input]
base_directory = "/docs/"
exclude_html_selector = "pre.language"
minimum_indexed_substring_length = 2
frontmatter_handling = "Omit"
stemming = "English"
title_boost = "Ridiculous"

[[input.files]]
path = '/home/peter/dev/Astro/astro-ui/docs/XElement/api/animate.md'
url = 'api/animate'
title = 'api animate'

[[input.files]]
path = '/home/peter/dev/Astro/astro-ui/docs/XElement/api/define_vars.md'
url = 'api/define_vars'
title = 'api define_vars'

[[input.files]]
path = '/home/peter/dev/Astro/astro-ui/docs/XElement/api/do.md'
url = 'api/do'
title = 'api do'

[[input.files]]
path = '/home/peter/dev/Astro/astro-ui/docs/XElement/api/event.md'
url = 'api/event'
title = 'api event'

[[input.files]]
path = '/home/peter/dev/Astro/astro-ui/docs/XElement/api/fetch.md'
url = 'api/fetch'
title = 'api fetch'

[[input.files]]
path = '/home/peter/dev/Astro/astro-ui/docs/XElement/api/import.md'
url = 'api/import'
title = 'api import'

[[input.files]]
path = '/home/peter/dev/Astro/astro-ui/docs/XElement/api/is.md'
url = 'api/is'
title = 'api is'

[[input.files]]
path = '/home/peter/dev/Astro/astro-ui/docs/XElement/api/observe.md'
url = 'api/observe'
title = 'api observe'

[[input.files]]
path = '/home/peter/dev/Astro/astro-ui/docs/XElement/api/overview.md'
url = 'api/overview'
title = 'api overview'

[[input.files]]
path = '/home/peter/dev/Astro/astro-ui/docs/XElement/api/properties.md'
url = 'api/properties'
title = 'api properties'

[[input.files]]
path = '/home/peter/dev/Astro/astro-ui/docs/XElement/api/resize.md'
url = 'api/resize'
title = 'api resize'

[[input.files]]
path = '/home/peter/dev/Astro/astro-ui/docs/XElement/api/store.md'
url = 'api/store'
title = 'api store'

[[input.files]]
path = '/home/peter/dev/Astro/astro-ui/docs/XElement/api/timings.md'
url = 'api/timings'
title = 'api timings'

[[input.files]]
path = '/home/peter/dev/Astro/astro-ui/docs/XElement/api/visible.md'
url = 'api/visible'
title = 'api visible'

[[input.files]]
path = '/home/peter/dev/Astro/astro-ui/docs/XElement/blog/interactivity.md'
url = 'blog/interactivity'
title = 'blog interactivity'

[[input.files]]
path = '/home/peter/dev/Astro/astro-ui/docs/XElement/blog/introduction.md'
url = 'blog/introduction'
title = 'blog introduction'

[[input.files]]
path = '/home/peter/dev/Astro/astro-ui/docs/XElement/blog/overview.md'
url = 'blog/overview'
title = 'blog overview'

[[input.files]]
path = '/home/peter/dev/Astro/astro-ui/docs/XElement/blog/xelement-v-framworks.md'
url = 'blog/xelement-v-framworks'
title = 'blog xelement-v-framworks'

[[input.files]]
path = '/home/peter/dev/Astro/astro-ui/docs/XElement/guides/animation.md'
url = 'guides/animation'
title = 'guides animation'

[[input.files]]
path = '/home/peter/dev/Astro/astro-ui/docs/XElement/guides/my-first-components.md'
url = 'guides/my-first-components'
title = 'guides my-first-components'

[[input.files]]
path = '/home/peter/dev/Astro/astro-ui/docs/XElement/guides/styling.md'
url = 'guides/styling'
title = 'guides styling'

[[input.files]]
path = '/home/peter/dev/Astro/astro-ui/docs/XElement/induction/events.md'
url = 'induction/events'
title = 'induction events'

[[input.files]]
path = '/home/peter/dev/Astro/astro-ui/docs/XElement/induction/getting-started.md'
url = 'induction/getting-started'
title = 'induction getting-started'

[[input.files]]
path = '/home/peter/dev/Astro/astro-ui/docs/XElement/induction/interactivity.md'
url = 'induction/interactivity'
title = 'induction interactivity'

[[input.files]]
path = '/home/peter/dev/Astro/astro-ui/docs/XElement/induction/introduction.md'
url = 'induction/introduction'
title = 'induction introduction'

[[input.files]]
path = '/home/peter/dev/Astro/astro-ui/docs/XElement/induction/methods.md'
url = 'induction/methods'
title = 'induction methods'

[[input.files]]
path = '/home/peter/dev/Astro/astro-ui/docs/XElement/induction/observations.md'
url = 'induction/observations'
title = 'induction observations'

[[input.files]]
path = '/home/peter/dev/Astro/astro-ui/docs/XElement/induction/overview.md'
url = 'induction/overview'
title = 'induction overview'

[[input.files]]
path = '/home/peter/dev/Astro/astro-ui/docs/XElement/induction/polymorphism.md'
url = 'induction/polymorphism'
title = 'induction polymorphism'



[output]
excerpt_buffer = 5
save_nearest_html_id = true
