
    [input]
    base_directory = "xelement-docs"
    url_prefix = "http://localhost:3000/docs/"
    exclude_html_selector = "pre.language"
    minimum_indexed_substring_length = 2
    frontmatter_handling = "Omit"
    stemming = "English"
    title_boost = "Ridiculous"
    files = [
        {path = '/home/peter/dev/Astro/astro-ui/docs/XElement/api/Overview.md',url = 'api/overview',title = 'api overview'},
{path = '/home/peter/dev/Astro/astro-ui/docs/XElement/api/Properties.md',url = 'api/properties',title = 'api properties'},
{path = '/home/peter/dev/Astro/astro-ui/docs/XElement/blog/Interactivity.md',url = 'blog/interactivity',title = 'blog interactivity'},
{path = '/home/peter/dev/Astro/astro-ui/docs/XElement/blog/Introduction.md',url = 'blog/introduction',title = 'blog introduction'},
{path = '/home/peter/dev/Astro/astro-ui/docs/XElement/blog/Overview.md',url = 'blog/overview',title = 'blog overview'},
{path = '/home/peter/dev/Astro/astro-ui/docs/XElement/blog/XElementvsFramworks.md',url = 'blog/xelementvsframworks',title = 'blog xelementvsframworks'},
{path = '/home/peter/dev/Astro/astro-ui/docs/XElement/examples/okikio.md',url = 'examples/okikio',title = 'examples okikio'},
{path = '/home/peter/dev/Astro/astro-ui/docs/XElement/guides/MyFirstComponents.md',url = 'guides/myfirstcomponents',title = 'guides myfirstcomponents'},
{path = '/home/peter/dev/Astro/astro-ui/docs/XElement/guides/Styling.md',url = 'guides/styling',title = 'guides styling'},
{path = '/home/peter/dev/Astro/astro-ui/docs/XElement/api/methods/animate.md',url = 'api/methods/animate',title = 'api methods animate'},
{path = '/home/peter/dev/Astro/astro-ui/docs/XElement/api/methods/define_vars.md',url = 'api/methods/define_vars',title = 'api methods define_vars'},
{path = '/home/peter/dev/Astro/astro-ui/docs/XElement/api/methods/do.md',url = 'api/methods/do',title = 'api methods do'},
{path = '/home/peter/dev/Astro/astro-ui/docs/XElement/api/methods/events.md',url = 'api/methods/events',title = 'api methods events'},
{path = '/home/peter/dev/Astro/astro-ui/docs/XElement/api/methods/fetch.md',url = 'api/methods/fetch',title = 'api methods fetch'},
{path = '/home/peter/dev/Astro/astro-ui/docs/XElement/api/methods/import.md',url = 'api/methods/import',title = 'api methods import'},
{path = '/home/peter/dev/Astro/astro-ui/docs/XElement/api/methods/observers.md',url = 'api/methods/observers',title = 'api methods observers'},
{path = '/home/peter/dev/Astro/astro-ui/docs/XElement/api/methods/overview.md',url = 'api/methods/overview',title = 'api methods overview'},
{path = '/home/peter/dev/Astro/astro-ui/docs/XElement/api/methods/store.md',url = 'api/methods/store',title = 'api methods store'},

    ]
    [output]
    excerpt_buffer = 5
    save_nearest_html_id = true
    