base_directory = "federalist"
url_prefix = "https://www.gutenberg.org/files/1404/1404-h/1404-h.htm#link2H_4_"

[[files]]
path = "federalist-1.txt"
url = "0001"
title = "General Introduction"

[[files]]
path = "federalist-2.txt"
url = "0002"
title = "Concerning Dangers from Foreign Force and Influence"

[[files]]
path = "federalist-3.txt"
url = "0003"
title = "Concerning Dangers from Foreign Force and Influence 2"

[[files]]
path = "federalist-4.txt"
url = "0004"
title = "Concerning Dangers from Foreign Force and Influence 3"

[[files]]
path = "/home/peter/dev/Astro/astro-ui/docs/XElement/api/methods/store.md"
url = "api/methods/store"
title = "api-methods-store"
verview"
s"
vars"
s"
